### ISSUE TITLE
Compile error on Auth Callback

### ISSUE THREAD

**Issue by sampurcell93** [birdcage/soundcloud-web-api-android#1]
Hi, I copied the code provided in the readme for onNewIntent in my MainActivity:

```
Authenticator auth =
            SoundCloudAuthenticator.handleResponse(intent, SC_RED, SC_ID, SC_SEC);
          SoundCloudAuthenticator.AuthService service = SoundCloudAuthenticator.getAuthService();
          service.authorize(auth, new Callback<AuthenticationResponse>() {
              @Override
              public void success(AuthenticationResponse authResponse, Response r) {
                  Log.v("AUTH SUCCESS", "TOKEN: " + authResponse.access_token);
                  // Save the token
              }

              @Override
              public void failure(RetrofitError error) {
                  Log.e("AUTH FAILED", "ERROR: " + error.getMessage());
                  // See what went wrong
              }
          });
```

 However, compile fails every time with the frustrating message:

```
error: <anonymous com.myproject.MainActivity$1> is not abstract and does not override abstract method success(AuthenticationResponse,Response) in Callback
          service.authorize(auth, new Callback<AuthenticationResponse>() {
                                                                         ^
/Users/samuelpurcell/Projects/myproject/android/app/src/main/java/com/myproject/MainActivity.java:118: error: method does not override or implement a method from a supertype
              @Override
```

I am importing Response as follows: `import com.squareup.okhttp.Response;`

Is there an obvious solution that I am missing? I have tried upgrading the retrofit and okhttp packages but to no avail. Am I using the wrong Response? Thanks for any help.

**Comment by jacoblubecki** [comment]
I believe the correct import is `import com.squareup.retrofit.client.Response;`. Either way, the response is a retrofit object that exists in the retrofit package somewhere. 

It's likely that your editor automatically imported the wrong class. Deleting the import and the `service.authorize` code, then retyping it manually might automatically import the class correctly. 

Hope that helps.

**Comment by sampurcell93** [comment]
Thanks for the quick response! `import retrofit.client.Response` seems to have done the trick as far as compilation goes... but now, when the authenticate callback is invoked, I am getting a 401 Unauthorized. Any ideas on that? I've looked at a good number of answers regarding 401s on SC and it seems like it might have something to do with making the request incorrectly? Any insight would be most appreciated.

EDIT: It looks like the package may need to use an application/x-form-urlencoded request, so it shouldn't be too difficult

**Comment by jacoblubecki** [comment]
Can you post any of the retrofit logs? The authenticator should be logging request and response details. Make sure to edit any sensitive out before pasting here (replace with #TOKEN#, #SECRET#, etc.).

**Comment by sampurcell93** [comment]
Here's the retrofit stuff:

```
04-07 18:39:26.358  9676 11405 D Retrofit: ---> HTTP POST https://api.soundcloud.com/oauth2/token
04-07 18:39:26.358  9676 11405 D Retrofit: Content-Type: application/json; charset=UTF-8
04-07 18:39:26.358  9676 11405 D Retrofit: Content-Length: 230
04-07 18:39:26.358  9676 11405 D Retrofit: {"client_id":"CLIENTID","client_secret":"SECRET","code":"be94b07c62f4db2c6a868d63b3e5d3ed","grant_type":"authorization_code","redirect_uri":"mycalback://soundcloud/redirect"}
04-07 18:39:26.358  9676 11405 D Retrofit: ---> END HTTP (230-byte body)


04-07 18:39:26.532  9676 11405 D Retrofit: <--- HTTP 401 https://api.soundcloud.com/oauth2/token (173ms)
04-07 18:39:26.532  9676 11405 D Retrofit: Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
04-07 18:39:26.532  9676 11405 D Retrofit: Access-Control-Allow-Methods: GET, PUT, POST, DELETE
04-07 18:39:26.532  9676 11405 D Retrofit: Access-Control-Allow-Origin: *
04-07 18:39:26.532  9676 11405 D Retrofit: Access-Control-Expose-Headers: Date
04-07 18:39:26.532  9676 11405 D Retrofit: Cache-Control: private, max-age=0, must-revalidate
04-07 18:39:26.532  9676 11405 D Retrofit: Date: Thu, 07 Apr 2016 22:39:21 GMT
04-07 18:39:26.532  9676 11405 D Retrofit: Server: am/2
04-07 18:39:26.532  9676 11405 D Retrofit: Content-Length: 0
04-07 18:39:26.532  9676 11405 D Retrofit: OkHttp-Selected-Protocol: http/1.1
04-07 18:39:26.532  9676 11405 D Retrofit: OkHttp-Sent-Millis: 1460068766425
04-07 18:39:26.532  9676 11405 D Retrofit: OkHttp-Received-Millis: 1460068766532
04-07 18:39:26.532  9676 11405 D Retrofit: <--- END HTTP (0-byte body)
```

EDIT: Relevant http://stackoverflow.com/questions/32898394/soundcloud-oauth2-token-returning-nothing-but-a-401-response

**Comment by jacoblubecki** [comment]
Hey sorry it's taken me so long to respond, I have pushed a hot fix to repair the broken authentication. After exams, I will be pushing a larger update with retrofit2 which will hopefully give me time to handle any other API changes. I understand if you've found another solution for now, but I hope that this will help you out if you're still using the library! Thanks again for the feedback!

**Comment by sampurcell93** [comment]
Hi, I've actually been meaning to make a PR, but I am not sure my solution is great (still don't have lots of experience in java). Thanks for getting back!
